initialzation:
  file:
    users:  users.json
    roles:  roles.json
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  notEmpty: true
spring: #数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/my_db
    username: root
    password: root
mybatis:
  configLocation: classpath:mybatis/configuration.xml
  mapperLocations: classpath:mybatis/mapper/*-mapper.xml
logging:
  level:
    org:
      springframework: WARN
    com:
      niuzj:
        springbootsecurity:
          dao: DEBUG


